# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/kube-openapi/cmd/openapi-gen"
]

[[override]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[override]]
  name = "github.com/json-iterator/go"
  version = "^1.1.5"
  # override set due to CaseSensitive option not being available in latest
  # stable version (1.1.3)

[[constraint]]
  name = "github.com/ligato/vpp-agent"
#  version = "1.7" # Version is set to match vpp-agent in use
#  # revision is set to match vpp-agent 1.7
  revision = "d2ae51e30bb34e5dec059de71c2d0f42ecb10a09"

[[override]]
  name = "github.com/vishvananda/netns"
  # revision is set because verioned release is missing 2 important fixes
  revision = "13995c7128ccc8e51e9a6bd2b551020a27180abd"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[override]]
  name = "google.golang.org/grpc"
  version = "1.2.1"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.3"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.12.3"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "9.0.0"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.2"

[[override]]
  name = "k8s.io/kubernetes"
  version = "^1.12.2"
  # kubernetes-1.11.1 resolves to b1b29978270dc22fecc592ac55d903350454310a
  # We set the revision to work around a transitive constraint issue introduced
  # in an interaction between k8s.io/client-go and k8s.io/kubernetes

[[constraint]]
  branch = "master"
  name = "k8s.io/kube-openapi"

[[constraint]]
  name = "github.com/go-errors/errors"
  version = "1.0.1"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    go-tests = false
    non-go = false

  [[prune.project]]
    name = "k8s.io/kube-openapi"
    unused-packages = false
    non-go = false

  [[prune.project]]
    name = "github.com/golang/protobuf"
    unused-packages = false
    go-tests = false
    non-go = false
