---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networkservicemanagers.networkservicemesh.io
spec:
  conversion:
    strategy: None
  group: networkservicemesh.io
  names:
    kind: NetworkServiceManager
    listKind: NetworkServiceManagerList
    plural: networkservicemanagers
    shortNames:
      - nsm
      - nsms
    singular: networkservicemanager
  scope: Namespaced
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
