---
# Default values for nsm-monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

registry: docker.io
org: networkservicemesh
tag: master
pullPolicy: IfNotPresent

# The type for monitoring services, i.e. Jaeger
# May be set to valid Kubernetes ServiceTypes values--ClusterIP, NodePort, LoadBalancer, ExternalName
monSvcType: ClusterIP
