---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networkserviceendpoints.networkservicemesh.io
spec:
  group: networkservicemesh.io
  names:
    kind: NetworkServiceEndpoint
    listKind: NetworkServiceEndpointList
    plural: networkserviceendpoints
    shortNames:
      - nse
      - nses
    singular: networkserviceendpoint
  scope: Cluster
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
