---
apiVersion: extensions/v1beta1
kind: DaemonSet
spec:
  template:
    metadata:
      labels:
        app: nsm-vpp-dataplane
    spec:
      hostPID: true
      hostNetwork: true
      containers:
        - name: vppagent-dataplane
          securityContext:
            privileged: true
          image: networkservicemesh/vppagent-dataplane:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: NSM_DATAPLANE_SRC_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: workspace
              mountPath: /var/lib/networkservicemesh/
              mountPropagation: Bidirectional
            - name: postmortem
              mountPath: /var/tmp/nsm-postmortem/
          livenessProbe:
            httpGet:
              path: /liveness
              port: 5555
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: 5555
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
      volumes:
        - hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
          name: workspace
        - hostPath:
            path: /var/tmp/nsm-postmortem/
            type: DirectoryOrCreate
          name: postmortem
metadata:
  name: nsm-vppagent-dataplane
  namespace: default
