---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io: "true"
      networkservicemesh.io/app: "vppagent-nsc"
  replicas: 2
  template:
    metadata:
      labels:
        networkservicemesh.io: "true"
        networkservicemesh.io/app: "vppagent-nsc"
    spec:
      hostPID: true
      containers:
        - name: vppagent-nsc
          image: networkservicemesh/vpp-test-common:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TEST_APPLICATION
              value: "vppagent-nsc"
            - name: CLIENT_LABELS
              value: "app=icmp"
            - name: CLIENT_NETWORK_SERVICE
              value: "icmp-responder"
          resources:
            limits:
              networkservicemesh.io/socket: 1
metadata:
  name: vppagent-nsc
  namespace: nsm-system
