---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "passthrough"
      networkservicemesh.io/impl: "secure-intranet-connectivity"
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "passthrough"
        networkservicemesh.io/impl: "secure-intranet-connectivity"
    spec:
      serviceAccount: nse-acc
      containers:
        - name: passthrough-nse
          image: networkservicemesh/vpp-test-common:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TEST_APPLICATION
              value: "vppagent-firewall-nse"
            - name: ENDPOINT_NETWORK_SERVICE
              value: "secure-intranet-connectivity"
            - name: ENDPOINT_LABELS
              value: "app=passthrough-1"
            - name: CLIENT_NETWORK_SERVICE
              value: "secure-intranet-connectivity"
            - name: OUTGOING_NSC_LABELS
              value: "app=passthrough-1"
            - name: TRACER_ENABLED
              value: "true"
          resources:
            limits:
              networkservicemesh.io/socket: 1
metadata:
  name: vppagent-passthrough-nse-1
  namespace: nsm-system
---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "passthrough"
      networkservicemesh.io/impl: "secure-intranet-connectivity"
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "passthrough"
        networkservicemesh.io/impl: "secure-intranet-connectivity"
    spec:
      serviceAccount: nse-acc
      containers:
        - name: passthrough-nse
          image: networkservicemesh/vpp-test-common:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TEST_APPLICATION
              value: "vppagent-firewall-nse"
            - name: ENDPOINT_NETWORK_SERVICE
              value: "secure-intranet-connectivity"
            - name: ENDPOINT_LABELS
              value: "app=passthrough-2"
            - name: CLIENT_NETWORK_SERVICE
              value: "secure-intranet-connectivity"
            - name: OUTGOING_NSC_LABELS
              value: "app=passthrough-2"
            - name: TRACER_ENABLED
              value: "true"
          resources:
            limits:
              networkservicemesh.io/socket: 1
metadata:
  name: vppagent-passthrough-nse-2
  namespace: nsm-system
---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "passthrough"
      networkservicemesh.io/impl: "secure-intranet-connectivity"
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "passthrough"
        networkservicemesh.io/impl: "secure-intranet-connectivity"
    spec:
      serviceAccount: nse-acc
      containers:
        - name: passthrough-nse
          image: networkservicemesh/vpp-test-common:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TEST_APPLICATION
              value: "vppagent-firewall-nse"
            - name: ENDPOINT_NETWORK_SERVICE
              value: "secure-intranet-connectivity"
            - name: ENDPOINT_LABELS
              value: "app=passthrough-3"
            - name: CLIENT_NETWORK_SERVICE
              value: "secure-intranet-connectivity"
            - name: OUTGOING_NSC_LABELS
              value: "app=passthrough-3"
            - name: TRACER_ENABLED
              value: "true"
          resources:
            limits:
              networkservicemesh.io/socket: 1
metadata:
  name: vppagent-passthrough-nse-3
  namespace: nsm-system
