---
# Default values for jaeger.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

pullPolicy: IfNotPresent
image: jaegertracing/all-in-one:1.14.0

# The type for monitoring services, i.e. Jaeger
# May be set to valid Kubernetes ServiceTypes values--ClusterIP, NodePort, LoadBalancer, ExternalName
monSvcType: ClusterIP

# Variable used to deploy Prometheus
# Values can be true or false
prometheus: false

metricsCollectorEnabled: false
